[mypy]
strict = True
disallow_subclassing_any = False
mypy_path = $MYPY_CONFIG_FILE_DIR
warn_redundant_casts = true
warn_unused_ignores = true
show_error_codes = true

[mypy-beancount_ai.server.pdf]
disallow_untyped_calls = False
