[tox]
envlist = basepython

[testenv]
setenv   =
    PYTHONPATH = {env:PYTHONPATH}{:}{toxinidir}
    MYPY_CACHE_DIR = {toxinidir}/.mypy_cache
deps =
    pytest
    mypy
    ruff
commands =
    pytest
    mypy -p beancount_ai
    ruff check beancount_ai/
