[tox]
envlist = basepython

[testenv]
setenv   =
    PYTHONPATH = {env:PYTHONPATH}{:}{toxinidir}
    MYPY_CACHE_DIR = {toxinidir}/.mypy_cache
deps =
    pytest
    mypy[faster-cache]
    ruff
commands =
    pytest -vv
    mypy -p beancount_ai
    ruff check --select I --select C beancount_ai/
